# create table for MySQL
CREATE TABLE IF NOT EXISTS `users`(
`id` INT UNSIGNED AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`gage` VARCHAR(100) NOT NULL,
PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `users_tbl`(
`id` INT UNSIGNED AUTO_INCREMENT,
`name` VARCHAR(100) NOT NULL,
`gage` VARCHAR(100) ,
`gage1` VARCHAR(100) ,
`gage2` VARCHAR(100) ,
`gage3` VARCHAR(100) ,
`gage4` VARCHAR(100) ,
`gage5` VARCHAR(100) ,
`gage6` VARCHAR(100) ,
`gage7` VARCHAR(100) ,
PRIMARY KEY ( `id` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

# create table for PostgreSQL
CREATE TABLE IF NOT EXISTS users(
id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL,
gage VARCHAR(100) NOT NULL,
PRIMARY KEY ( id )
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS users_tbl(
id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(100) NOT NULL,
gage VARCHAR(100) NOT NULL,
gage1 VARCHAR(100) NOT NULL,
gage2 VARCHAR(100) NOT NULL,
gage3 VARCHAR(100) NOT NULL,
gage4 VARCHAR(100) NOT NULL,
gage5 VARCHAR(100) NOT NULL,
gage6 VARCHAR(100) NOT NULL,
gage7 VARCHAR(100) NOT NULL);